#!/bin/sh

DEFAULT_INSTALL_DIR=/usr/bin

install_local() {
  sudo mv huff $DEFAULT_INSTALL_DIR
  echo "huff successfully installed!"
}

print_usage() {
  echo "Huff is a package management utility that delegates to other package management utilities."
  echo
  echo "  Usage:"
  echo "    huff command [arguments...] [options...]"
  echo
  echo "  Examples:"
  echo "    huff install curl"
  echo  
}

search_brew() {
  if [ $(which brew) ]
  then
    result=$(brew search $1)
    results=(${result// / })
    for var in "${results[@]}"
    do
      if [ $1 == $var ]
      then
        return 1
      fi
    done
    return 0
  fi
  return 0
}

search_pip() {
  if [ $(which pip) ]
  then
    result=$(pip search $1 | awk '{ print $1 }')
    results=($result// / })
    for var in "${results[@]}"
    do
      if [ $1 == $var ]
      then
        return 1
      fi
    done
    return 0
  fi
  return 0
}

install() {
  search_brew $1
  found=$?
  if [ $found -eq 1 ]
  then
    echo "$1 found in brew"
    brew install $1
  fi
  search_pip $1
  found=$?
  if [ $found -eq 1 ]
  then
    echo "$1 found in pip"
    pip install $1
  fi
}

if [ $# -eq 0 ]
then
  print_usage
  exit
fi


if [ $1 == "--install-local" ]
then
  install_local
elif [ $1 == "install" ]
then
  install $2
fi

