#!/bin/sh

DEFAULT_INSTALL_DIR=/usr/bin

install_local() {
  sudo mv huff $DEFAULT_INSTALL_DIR
  echo "huff successfully installed!"
}

print_usage() {
  echo "usage!"
}

if [ $# -eq 0 ]
then
  print_usage
  exit
fi

if [ $1 == "--install-local" ]
then
  install_local
else
  echo "not so sweet"
fi

